// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ways a user receives notification
type NotificationMethod int32

const (
	NotificationMethod_EMAIL_AND_PHONE NotificationMethod = 0
	NotificationMethod_EMAIL_ONLY      NotificationMethod = 1
	NotificationMethod_PHONE_ONLY      NotificationMethod = 2
)

var NotificationMethod_name = map[int32]string{
	0: "EMAIL_AND_PHONE",
	1: "EMAIL_ONLY",
	2: "PHONE_ONLY",
}

var NotificationMethod_value = map[string]int32{
	"EMAIL_AND_PHONE": 0,
	"EMAIL_ONLY":      1,
	"PHONE_ONLY":      2,
}

func (x NotificationMethod) String() string {
	return proto.EnumName(NotificationMethod_name, int32(x))
}

func (NotificationMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

// AdminLevel is the administrative level of an admin
type AdminLevel int32

const (
	AdminLevel_READER               AdminLevel = 0
	AdminLevel_READER_AND_ONLY_FOOD AdminLevel = 1
	AdminLevel_SUPER_ADMIN          AdminLevel = 2
)

var AdminLevel_name = map[int32]string{
	0: "READER",
	1: "READER_AND_ONLY_FOOD",
	2: "SUPER_ADMIN",
}

var AdminLevel_value = map[string]int32{
	"READER":               0,
	"READER_AND_ONLY_FOOD": 1,
	"SUPER_ADMIN":          2,
}

func (x AdminLevel) String() string {
	return proto.EnumName(AdminLevel_name, int32(x))
}

func (AdminLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

// Profile contains user information
type Profile struct {
	FirstName              string             `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName               string             `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber            string             `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailAddress           string             `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ProfileUrl             string             `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	BirthDate              string             `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender                 string             `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	NotificationMethod     NotificationMethod `protobuf:"varint,8,opt,name=notification_method,json=notificationMethod,proto3,enum=rupacinema.account.NotificationMethod" json:"notification_method,omitempty"`
	SubscribeNotifications map[string]bool    `protobuf:"bytes,9,rep,name=subscribe_notifications,json=subscribeNotifications,proto3" json:"subscribe_notifications,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}           `json:"-"`
	XXX_unrecognized       []byte             `json:"-"`
	XXX_sizecache          int32              `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Profile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Profile) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *Profile) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetNotificationMethod() NotificationMethod {
	if m != nil {
		return m.NotificationMethod
	}
	return NotificationMethod_EMAIL_AND_PHONE
}

func (m *Profile) GetSubscribeNotifications() map[string]bool {
	if m != nil {
		return m.SubscribeNotifications
	}
	return nil
}

// PrivateProfile contains private account information
type PrivateProfile struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	SecurityQuestion     string   `protobuf:"bytes,2,opt,name=security_question,json=securityQuestion,proto3" json:"security_question,omitempty"`
	SecurityAnswer       string   `protobuf:"bytes,3,opt,name=security_answer,json=securityAnswer,proto3" json:"security_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateProfile) Reset()         { *m = PrivateProfile{} }
func (m *PrivateProfile) String() string { return proto.CompactTextString(m) }
func (*PrivateProfile) ProtoMessage()    {}
func (*PrivateProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *PrivateProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateProfile.Unmarshal(m, b)
}
func (m *PrivateProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateProfile.Marshal(b, m, deterministic)
}
func (m *PrivateProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateProfile.Merge(m, src)
}
func (m *PrivateProfile) XXX_Size() int {
	return xxx_messageInfo_PrivateProfile.Size(m)
}
func (m *PrivateProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateProfile proto.InternalMessageInfo

func (m *PrivateProfile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PrivateProfile) GetSecurityQuestion() string {
	if m != nil {
		return m.SecurityQuestion
	}
	return ""
}

func (m *PrivateProfile) GetSecurityAnswer() string {
	if m != nil {
		return m.SecurityAnswer
	}
	return ""
}

// Facebook is request payload to login with facebook account
type Facebook struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailAddress         string   `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ProfileUrl           string   `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate            string   `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facebook) Reset()         { *m = Facebook{} }
func (m *Facebook) String() string { return proto.CompactTextString(m) }
func (*Facebook) ProtoMessage()    {}
func (*Facebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *Facebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facebook.Unmarshal(m, b)
}
func (m *Facebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facebook.Marshal(b, m, deterministic)
}
func (m *Facebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facebook.Merge(m, src)
}
func (m *Facebook) XXX_Size() int {
	return xxx_messageInfo_Facebook.Size(m)
}
func (m *Facebook) XXX_DiscardUnknown() {
	xxx_messageInfo_Facebook.DiscardUnknown(m)
}

var xxx_messageInfo_Facebook proto.InternalMessageInfo

func (m *Facebook) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Facebook) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Facebook) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Facebook) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Facebook) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *Facebook) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Facebook) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

// Google is request payload to login using google account
type Google struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailAddress         string   `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ProfileUrl           string   `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate            string   `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Google) Reset()         { *m = Google{} }
func (m *Google) String() string { return proto.CompactTextString(m) }
func (*Google) ProtoMessage()    {}
func (*Google) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Google) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Google.Unmarshal(m, b)
}
func (m *Google) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Google.Marshal(b, m, deterministic)
}
func (m *Google) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Google.Merge(m, src)
}
func (m *Google) XXX_Size() int {
	return xxx_messageInfo_Google.Size(m)
}
func (m *Google) XXX_DiscardUnknown() {
	xxx_messageInfo_Google.DiscardUnknown(m)
}

var xxx_messageInfo_Google proto.InternalMessageInfo

func (m *Google) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Google) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Google) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Google) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Google) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *Google) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Google) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

// Phone is request payload to login using phone number
type Phone struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Phone) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Request to login
type LoginRequest struct {
	// User to use one of the options only.
	//
	// Types that are valid to be assigned to Login:
	//	*LoginRequest_Facebook
	//	*LoginRequest_Google
	//	*LoginRequest_Phone
	Login                isLoginRequest_Login `protobuf_oneof:"login"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type isLoginRequest_Login interface {
	isLoginRequest_Login()
}

type LoginRequest_Facebook struct {
	Facebook *Facebook `protobuf:"bytes,1,opt,name=facebook,proto3,oneof"`
}

type LoginRequest_Google struct {
	Google *Google `protobuf:"bytes,2,opt,name=google,proto3,oneof"`
}

type LoginRequest_Phone struct {
	Phone *Phone `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*LoginRequest_Facebook) isLoginRequest_Login() {}

func (*LoginRequest_Google) isLoginRequest_Login() {}

func (*LoginRequest_Phone) isLoginRequest_Login() {}

func (m *LoginRequest) GetLogin() isLoginRequest_Login {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *LoginRequest) GetFacebook() *Facebook {
	if x, ok := m.GetLogin().(*LoginRequest_Facebook); ok {
		return x.Facebook
	}
	return nil
}

func (m *LoginRequest) GetGoogle() *Google {
	if x, ok := m.GetLogin().(*LoginRequest_Google); ok {
		return x.Google
	}
	return nil
}

func (m *LoginRequest) GetPhone() *Phone {
	if x, ok := m.GetLogin().(*LoginRequest_Phone); ok {
		return x.Phone
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginRequest_Facebook)(nil),
		(*LoginRequest_Google)(nil),
		(*LoginRequest_Phone)(nil),
	}
}

// LoginResponse contains jwt token on successful login
type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Request to create an account
type CreateUserRequest struct {
	// request_id to detect duplicate requests
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// User profile information
	Profile *Profile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	// Private information
	PrivateProfile       *PrivateProfile `protobuf:"bytes,3,opt,name=private_profile,json=privateProfile,proto3" json:"private_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateUserRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *CreateUserRequest) GetPrivateProfile() *PrivateProfile {
	if m != nil {
		return m.PrivateProfile
	}
	return nil
}

// Request to get the default token
type GetDefaultTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDefaultTokenRequest) Reset()         { *m = GetDefaultTokenRequest{} }
func (m *GetDefaultTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefaultTokenRequest) ProtoMessage()    {}
func (*GetDefaultTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *GetDefaultTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefaultTokenRequest.Unmarshal(m, b)
}
func (m *GetDefaultTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefaultTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetDefaultTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefaultTokenRequest.Merge(m, src)
}
func (m *GetDefaultTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetDefaultTokenRequest.Size(m)
}
func (m *GetDefaultTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefaultTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefaultTokenRequest proto.InternalMessageInfo

// Request to retrive user profile, using either email or phone
type GetUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// Request to authenticate a user
type AuthenticateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(m, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// Response from AuthenticateUser request
type AuthenticateResponse struct {
	// whether the user validation was successful
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Request to retrieve multiple users resources
type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

// Admin represents administrator user
type Admin struct {
	FirstName            string     `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string     `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string     `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailAddress         string     `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	UserName             string     `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Level                AdminLevel `protobuf:"varint,6,opt,name=level,proto3,enum=rupacinema.account.AdminLevel" json:"level,omitempty"`
	TrustedDevices       []string   `protobuf:"bytes,7,rep,name=trusted_devices,json=trustedDevices,proto3" json:"trusted_devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Admin) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Admin) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Admin) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Admin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Admin) GetLevel() AdminLevel {
	if m != nil {
		return m.Level
	}
	return AdminLevel_READER
}

func (m *Admin) GetTrustedDevices() []string {
	if m != nil {
		return m.TrustedDevices
	}
	return nil
}

// Request to login the admin
type LoginAdminRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminRequest) Reset()         { *m = LoginAdminRequest{} }
func (m *LoginAdminRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAdminRequest) ProtoMessage()    {}
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *LoginAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminRequest.Unmarshal(m, b)
}
func (m *LoginAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminRequest.Marshal(b, m, deterministic)
}
func (m *LoginAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminRequest.Merge(m, src)
}
func (m *LoginAdminRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAdminRequest.Size(m)
}
func (m *LoginAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminRequest proto.InternalMessageInfo

func (m *LoginAdminRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Request to create a new admin
type CreateAdminRequest struct {
	SuperAdminUsername   string          `protobuf:"bytes,1,opt,name=super_admin_username,json=superAdminUsername,proto3" json:"super_admin_username,omitempty"`
	NewAdmin             *Admin          `protobuf:"bytes,2,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	AdminPrivate         *PrivateProfile `protobuf:"bytes,3,opt,name=admin_private,json=adminPrivate,proto3" json:"admin_private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAdminRequest) Reset()         { *m = CreateAdminRequest{} }
func (m *CreateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRequest) ProtoMessage()    {}
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *CreateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRequest.Unmarshal(m, b)
}
func (m *CreateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRequest.Merge(m, src)
}
func (m *CreateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRequest.Size(m)
}
func (m *CreateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRequest proto.InternalMessageInfo

func (m *CreateAdminRequest) GetSuperAdminUsername() string {
	if m != nil {
		return m.SuperAdminUsername
	}
	return ""
}

func (m *CreateAdminRequest) GetNewAdmin() *Admin {
	if m != nil {
		return m.NewAdmin
	}
	return nil
}

func (m *CreateAdminRequest) GetAdminPrivate() *PrivateProfile {
	if m != nil {
		return m.AdminPrivate
	}
	return nil
}

// Request to get admin profile
type GetAdminRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminRequest) Reset()         { *m = GetAdminRequest{} }
func (m *GetAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdminRequest) ProtoMessage()    {}
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *GetAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminRequest.Unmarshal(m, b)
}
func (m *GetAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminRequest.Marshal(b, m, deterministic)
}
func (m *GetAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminRequest.Merge(m, src)
}
func (m *GetAdminRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdminRequest.Size(m)
}
func (m *GetAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminRequest proto.InternalMessageInfo

func (m *GetAdminRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

// Request to authenticate admin
type AuthenticateAdminRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateAdminRequest) Reset()         { *m = AuthenticateAdminRequest{} }
func (m *AuthenticateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateAdminRequest) ProtoMessage()    {}
func (*AuthenticateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{17}
}

func (m *AuthenticateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateAdminRequest.Unmarshal(m, b)
}
func (m *AuthenticateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateAdminRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateAdminRequest.Merge(m, src)
}
func (m *AuthenticateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateAdminRequest.Size(m)
}
func (m *AuthenticateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateAdminRequest proto.InternalMessageInfo

func (m *AuthenticateAdminRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterEnum("rupacinema.account.NotificationMethod", NotificationMethod_name, NotificationMethod_value)
	proto.RegisterEnum("rupacinema.account.AdminLevel", AdminLevel_name, AdminLevel_value)
	proto.RegisterType((*Profile)(nil), "rupacinema.account.Profile")
	proto.RegisterMapType((map[string]bool)(nil), "rupacinema.account.Profile.SubscribeNotificationsEntry")
	proto.RegisterType((*PrivateProfile)(nil), "rupacinema.account.PrivateProfile")
	proto.RegisterType((*Facebook)(nil), "rupacinema.account.Facebook")
	proto.RegisterType((*Google)(nil), "rupacinema.account.Google")
	proto.RegisterType((*Phone)(nil), "rupacinema.account.Phone")
	proto.RegisterType((*LoginRequest)(nil), "rupacinema.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "rupacinema.account.LoginResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "rupacinema.account.CreateUserRequest")
	proto.RegisterType((*GetDefaultTokenRequest)(nil), "rupacinema.account.GetDefaultTokenRequest")
	proto.RegisterType((*GetUserRequest)(nil), "rupacinema.account.GetUserRequest")
	proto.RegisterType((*AuthenticateUserRequest)(nil), "rupacinema.account.AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "rupacinema.account.AuthenticateResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "rupacinema.account.ListUsersRequest")
	proto.RegisterType((*Admin)(nil), "rupacinema.account.Admin")
	proto.RegisterType((*LoginAdminRequest)(nil), "rupacinema.account.LoginAdminRequest")
	proto.RegisterType((*CreateAdminRequest)(nil), "rupacinema.account.CreateAdminRequest")
	proto.RegisterType((*GetAdminRequest)(nil), "rupacinema.account.GetAdminRequest")
	proto.RegisterType((*AuthenticateAdminRequest)(nil), "rupacinema.account.AuthenticateAdminRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 1305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4d, 0x53, 0xdb, 0x56,
	0x17, 0x46, 0xe6, 0xf5, 0xd7, 0x31, 0x18, 0x73, 0xc3, 0x80, 0x62, 0x42, 0x42, 0x6e, 0xbe, 0x18,
	0x92, 0x98, 0xbc, 0x34, 0x4d, 0xdb, 0x4c, 0x37, 0x4e, 0xec, 0x00, 0x13, 0x62, 0xa8, 0x52, 0xa6,
	0xd3, 0x6e, 0x34, 0xb2, 0x7d, 0x31, 0x6a, 0x64, 0x49, 0xd1, 0xbd, 0x82, 0x61, 0x9a, 0x6e, 0xb2,
	0xe9, 0xaa, 0x33, 0x9d, 0xe9, 0x7f, 0xe9, 0xaa, 0xfb, 0x6e, 0xba, 0xeb, 0x5f, 0xc8, 0xf4, 0x4f,
	0x74, 0xd3, 0xd1, 0xb9, 0x57, 0x46, 0xc2, 0x82, 0xd0, 0xae, 0xda, 0xae, 0xe0, 0x9e, 0x73, 0xee,
	0x7d, 0xce, 0xc7, 0x73, 0x1e, 0x0b, 0xa6, 0xad, 0x5e, 0xcf, 0x0b, 0x5d, 0xd1, 0xf0, 0x03, 0x4f,
	0x78, 0x84, 0x04, 0xa1, 0x6f, 0xf5, 0x6c, 0x97, 0x0d, 0xad, 0x86, 0xf2, 0xd4, 0x17, 0x07, 0x9e,
	0x37, 0x70, 0xd8, 0x1a, 0x46, 0x74, 0xc3, 0xfd, 0x35, 0x36, 0xf4, 0xc5, 0xb1, 0xbc, 0x50, 0xbf,
	0xa2, 0x9c, 0x96, 0x6f, 0xaf, 0x59, 0xae, 0xeb, 0x09, 0x4b, 0xd8, 0x9e, 0xcb, 0x95, 0xf7, 0x1e,
	0xfe, 0xe9, 0xdd, 0x1f, 0x30, 0xf7, 0x3e, 0x3f, 0xb2, 0x06, 0x03, 0x16, 0xac, 0x79, 0x3e, 0x46,
	0x8c, 0x47, 0xd3, 0x3f, 0x26, 0xa1, 0xb8, 0x1b, 0x78, 0xfb, 0xb6, 0xc3, 0xc8, 0x12, 0xc0, 0xbe,
	0x1d, 0x70, 0x61, 0xba, 0xd6, 0x90, 0xe9, 0xda, 0xb2, 0xb6, 0x52, 0x36, 0xca, 0x68, 0xe9, 0x58,
	0x43, 0x46, 0x16, 0xa1, 0xec, 0x58, 0xb1, 0x37, 0x87, 0xde, 0x52, 0x64, 0x40, 0xe7, 0x75, 0x98,
	0xf2, 0x0f, 0x3c, 0x97, 0x99, 0x6e, 0x38, 0xec, 0xb2, 0x40, 0x9f, 0x44, 0x7f, 0x05, 0x6d, 0x1d,
	0x34, 0x91, 0x1b, 0x30, 0xcd, 0x86, 0x96, 0xed, 0x98, 0x56, 0xbf, 0x1f, 0x30, 0xce, 0xf5, 0xff,
	0x61, 0xcc, 0x14, 0x1a, 0x9b, 0xd2, 0x46, 0xae, 0x41, 0xc5, 0x97, 0xe9, 0x98, 0x61, 0xe0, 0xe8,
	0x79, 0x0c, 0x01, 0x65, 0xda, 0x0b, 0x9c, 0x28, 0xc9, 0xae, 0x1d, 0x88, 0x03, 0xb3, 0x6f, 0x09,
	0xa6, 0x17, 0x64, 0x92, 0x68, 0x69, 0x59, 0x82, 0x91, 0x79, 0x28, 0x0c, 0x98, 0xdb, 0x67, 0x81,
	0x5e, 0x44, 0x97, 0x3a, 0x91, 0x2f, 0xe0, 0x92, 0xeb, 0x09, 0x7b, 0xdf, 0xee, 0x61, 0xf9, 0xe6,
	0x90, 0x89, 0x03, 0xaf, 0xaf, 0x97, 0x96, 0xb5, 0x95, 0xea, 0xfa, 0xed, 0xc6, 0xf8, 0x08, 0x1a,
	0x9d, 0x44, 0xf8, 0x0b, 0x8c, 0x36, 0x88, 0x3b, 0x66, 0x23, 0x3e, 0x2c, 0xf0, 0xb0, 0xcb, 0x7b,
	0x81, 0xdd, 0x65, 0x66, 0xd2, 0xcf, 0xf5, 0xf2, 0xf2, 0xe4, 0x4a, 0x65, 0xfd, 0xa3, 0xac, 0xc7,
	0x55, 0xcb, 0x1b, 0x2f, 0xe3, 0xab, 0x49, 0x34, 0xde, 0x76, 0x45, 0x70, 0x6c, 0xcc, 0xf3, 0x4c,
	0x67, 0x7d, 0x0b, 0x16, 0xcf, 0xb9, 0x46, 0x6a, 0x30, 0xf9, 0x8a, 0x1d, 0xab, 0xf1, 0x45, 0xff,
	0x92, 0x39, 0xc8, 0x1f, 0x5a, 0x4e, 0x28, 0x87, 0x56, 0x32, 0xe4, 0xe1, 0x71, 0xee, 0x63, 0x8d,
	0xbe, 0xd5, 0xa0, 0xba, 0x1b, 0xd8, 0x87, 0x96, 0x60, 0x31, 0x09, 0xea, 0x50, 0xf2, 0x2d, 0xce,
	0x8f, 0xbc, 0xa0, 0xaf, 0xde, 0x18, 0x9d, 0xc9, 0x5d, 0x98, 0xe5, 0xac, 0x17, 0x06, 0xb6, 0x38,
	0x36, 0x5f, 0x87, 0x8c, 0x47, 0xa8, 0x8a, 0x09, 0xb5, 0xd8, 0xf1, 0x99, 0xb2, 0x93, 0x3b, 0x30,
	0x33, 0x0a, 0xb6, 0x5c, 0x7e, 0x34, 0x22, 0x45, 0x35, 0x36, 0x37, 0xd1, 0x4a, 0x7f, 0xd7, 0xa0,
	0xf4, 0xcc, 0xea, 0xb1, 0xae, 0xe7, 0xbd, 0xfa, 0x77, 0x70, 0xf0, 0x84, 0x64, 0x85, 0x14, 0xc9,
	0xd2, 0xdc, 0x2c, 0x9e, 0xe2, 0x26, 0x7d, 0xa7, 0x41, 0x61, 0x03, 0x57, 0xf7, 0x3f, 0x5d, 0xe6,
	0x27, 0x90, 0xdf, 0x8d, 0x72, 0x89, 0x78, 0x87, 0x49, 0xa9, 0xfa, 0xe4, 0x21, 0x45, 0xb0, 0x5c,
	0x9a, 0x60, 0xf4, 0x67, 0x0d, 0xa6, 0xb6, 0xbd, 0x81, 0xed, 0x1a, 0x0c, 0xf9, 0x45, 0x1e, 0x43,
	0x69, 0x5f, 0x51, 0x03, 0x5f, 0xa9, 0xac, 0x5f, 0xc9, 0x5a, 0xa7, 0x98, 0x3e, 0x9b, 0x13, 0xc6,
	0x28, 0x9e, 0x3c, 0x84, 0x82, 0x14, 0x4a, 0x84, 0xa9, 0xac, 0xd7, 0xb3, 0x6e, 0xca, 0x79, 0x6c,
	0x4e, 0x18, 0x2a, 0x96, 0xfc, 0x3f, 0x4e, 0x7a, 0x12, 0x2f, 0x5d, 0xce, 0xdc, 0xde, 0x28, 0x60,
	0x73, 0x42, 0x55, 0xf4, 0xa4, 0x08, 0x79, 0x27, 0x4a, 0x9a, 0xde, 0x82, 0x69, 0x95, 0x3d, 0xf7,
	0x3d, 0x97, 0x63, 0x07, 0x84, 0xf7, 0x8a, 0xb9, 0x71, 0x07, 0xf0, 0x40, 0x7f, 0xd2, 0x60, 0xf6,
	0x69, 0xc0, 0x2c, 0xc1, 0xf6, 0x38, 0x0b, 0xe2, 0x52, 0x97, 0x00, 0x02, 0xf9, 0xaf, 0x69, 0xc7,
	0xab, 0x57, 0x56, 0x96, 0xad, 0x3e, 0xf9, 0x10, 0x8a, 0x6a, 0x34, 0xaa, 0x9c, 0xc5, 0x73, 0x74,
	0xc5, 0x88, 0x63, 0xc9, 0x73, 0x98, 0xf1, 0xe5, 0x82, 0x9b, 0xf1, 0x75, 0x59, 0x18, 0xcd, 0xbe,
	0x9e, 0xd4, 0x02, 0xa3, 0xea, 0xa7, 0xce, 0x54, 0x87, 0xf9, 0x0d, 0x26, 0x5a, 0x6c, 0xdf, 0x0a,
	0x1d, 0xf1, 0x79, 0x54, 0x8b, 0x4a, 0x9e, 0x7e, 0x0a, 0xd5, 0x0d, 0x26, 0x92, 0xe5, 0xcc, 0x41,
	0x1e, 0xd9, 0x16, 0x97, 0x8e, 0x87, 0x13, 0x4a, 0xe4, 0x12, 0x94, 0xa0, 0x6d, 0x58, 0x68, 0x86,
	0xe2, 0x80, 0xb9, 0x22, 0x92, 0x32, 0xf6, 0x77, 0x9f, 0xb9, 0x07, 0x73, 0xc9, 0x67, 0x92, 0x53,
	0x38, 0xb4, 0x1c, 0xd5, 0x54, 0xa9, 0x7f, 0x76, 0x9f, 0x12, 0xa8, 0x6d, 0xdb, 0x1c, 0x73, 0xe6,
	0x71, 0x19, 0xdf, 0xe5, 0x20, 0xdf, 0xec, 0x0f, 0x6d, 0xf7, 0x1f, 0xb1, 0xa0, 0x8b, 0x50, 0x0e,
	0x39, 0x0b, 0x24, 0x88, 0x5c, 0xcf, 0x52, 0x64, 0x40, 0x90, 0x87, 0x90, 0x77, 0xd8, 0x21, 0x73,
	0x70, 0x37, 0xab, 0xeb, 0x57, 0xb3, 0xc6, 0x89, 0xa5, 0x6c, 0x47, 0x51, 0x86, 0x0c, 0x8e, 0x44,
	0x59, 0x04, 0x21, 0x17, 0xac, 0x6f, 0xf6, 0xd9, 0xa1, 0xdd, 0x63, 0x5c, 0x2f, 0x2e, 0x4f, 0x46,
	0xa2, 0xac, 0xcc, 0x2d, 0x69, 0xa5, 0xcf, 0x61, 0x16, 0xa9, 0x8c, 0x4f, 0xc4, 0xc3, 0xa8, 0x03,
	0xe2, 0x27, 0x5a, 0x32, 0x3a, 0x9f, 0xbb, 0xd6, 0xbf, 0x68, 0x40, 0x24, 0xe1, 0x53, 0xcf, 0x3d,
	0x80, 0x39, 0x1e, 0xfa, 0x2c, 0x30, 0xad, 0xc8, 0x6a, 0x9e, 0x7a, 0x9a, 0xa0, 0x0f, 0x2f, 0xec,
	0xc5, 0x20, 0x8f, 0xa0, 0xec, 0xb2, 0x23, 0x19, 0xaf, 0xd6, 0xe0, 0xf2, 0x99, 0x85, 0x1b, 0x25,
	0x97, 0x1d, 0xc9, 0x69, 0x6e, 0xc0, 0xb4, 0xc4, 0x50, 0x84, 0xfe, 0x0b, 0x3b, 0x30, 0x85, 0x17,
	0x95, 0x91, 0x36, 0x60, 0x66, 0x83, 0x89, 0x54, 0x15, 0xa9, 0x29, 0x69, 0xe9, 0x29, 0xd1, 0x47,
	0xa0, 0x27, 0x29, 0x79, 0xd1, 0x6e, 0xae, 0x6e, 0x01, 0x19, 0xff, 0xfe, 0x20, 0x97, 0x60, 0xa6,
	0xfd, 0xa2, 0xb9, 0xb5, 0x6d, 0x36, 0x3b, 0x2d, 0x73, 0x77, 0x73, 0xa7, 0xd3, 0xae, 0x4d, 0x90,
	0x2a, 0x80, 0x34, 0xee, 0x74, 0xb6, 0xbf, 0xac, 0x69, 0xd1, 0x19, 0x5d, 0xf2, 0x9c, 0x5b, 0x7d,
	0x0a, 0x70, 0xc2, 0x03, 0x02, 0x50, 0x30, 0xda, 0xcd, 0x56, 0xdb, 0xa8, 0x4d, 0x10, 0x1d, 0xe6,
	0xe4, 0xff, 0xf8, 0x5e, 0x14, 0x6e, 0x3e, 0xdb, 0xd9, 0x69, 0xd5, 0x34, 0x32, 0x03, 0x95, 0x97,
	0x7b, 0xbb, 0x91, 0xa3, 0xf5, 0x62, 0xab, 0x53, 0xcb, 0xad, 0xff, 0x5a, 0x06, 0x68, 0xca, 0x06,
	0x35, 0x77, 0xb7, 0xc8, 0x6b, 0xc8, 0x23, 0x3b, 0xc8, 0x72, 0x56, 0x07, 0x93, 0x0a, 0x5e, 0xbf,
	0x7e, 0x4e, 0x84, 0xdc, 0x4f, 0x7a, 0xe3, 0xed, 0x6f, 0xef, 0x7e, 0xcc, 0x2d, 0x51, 0x5d, 0x7e,
	0xd1, 0xca, 0x98, 0xb5, 0xa8, 0x17, 0x7c, 0x0d, 0x85, 0xf5, 0xb1, 0xb6, 0x4a, 0xbe, 0x06, 0x38,
	0xd1, 0x4c, 0x72, 0x2b, 0xeb, 0xd5, 0x31, 0x4d, 0xad, 0xcf, 0x37, 0xa4, 0xaa, 0x37, 0xe2, 0xef,
	0xe8, 0x46, 0x3b, 0xfa, 0x8e, 0xa6, 0x4b, 0x88, 0xb8, 0x40, 0xc9, 0x38, 0x62, 0x84, 0xf5, 0x06,
	0xa7, 0x9c, 0xd4, 0x39, 0xb2, 0x9a, 0xf9, 0xe3, 0x91, 0x29, 0x86, 0x17, 0x29, 0xb9, 0x8e, 0x09,
	0xcc, 0x91, 0x74, 0x02, 0xf8, 0xf3, 0x40, 0x5c, 0x28, 0x2a, 0x2d, 0x25, 0xf4, 0x0c, 0xd4, 0x64,
	0x8d, 0xe7, 0xfd, 0x0e, 0x50, 0x8a, 0x38, 0x57, 0x48, 0x3d, 0xa3, 0xb5, 0xf1, 0x4f, 0xc4, 0xf7,
	0x1a, 0xd4, 0x4e, 0xcb, 0x2f, 0xb9, 0x9b, 0xb9, 0x56, 0xd9, 0x22, 0x5d, 0x5f, 0x79, 0x5f, 0xf0,
	0xa8, 0x6e, 0x95, 0x0f, 0x5d, 0xc8, 0xc8, 0xc7, 0x0a, 0xc5, 0x41, 0xd4, 0x7d, 0x07, 0xca, 0x23,
	0x61, 0x26, 0x37, 0x33, 0x7b, 0x79, 0x4a, 0xb7, 0xcf, 0xef, 0x41, 0x76, 0xaf, 0x11, 0xf3, 0x81,
	0x46, 0xde, 0x00, 0x9c, 0x08, 0x5d, 0x36, 0xaf, 0xc6, 0x84, 0xf0, 0x22, 0x13, 0xbe, 0x89, 0xa8,
	0x57, 0xe9, 0xe5, 0x14, 0x2a, 0x8a, 0x49, 0x82, 0xd5, 0x43, 0xa8, 0x24, 0x84, 0x91, 0xdc, 0x3e,
	0x9b, 0xd6, 0x29, 0xfc, 0xb3, 0x78, 0x7d, 0x15, 0x41, 0x75, 0x7a, 0x29, 0x03, 0x34, 0x82, 0xe3,
	0x50, 0x8a, 0xe5, 0x8b, 0xdc, 0x38, 0x83, 0x5b, 0x29, 0xa0, 0xb3, 0xd5, 0x95, 0xde, 0x41, 0xac,
	0xeb, 0xe4, 0x5a, 0x56, 0x81, 0xdf, 0x8c, 0x24, 0xf1, 0x5b, 0xf2, 0x83, 0x06, 0xb3, 0x63, 0x22,
	0x48, 0xee, 0xbd, 0x8f, 0x33, 0xa9, 0x3c, 0x2e, 0xce, 0xb0, 0x6c, 0x31, 0x51, 0x69, 0x29, 0x8a,
	0x3d, 0x29, 0x7f, 0x55, 0x54, 0x9e, 0x6e, 0x01, 0x5b, 0xf8, 0xc1, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0xb2, 0x88, 0x49, 0x95, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountAPIClient is the client API for AccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountAPIClient interface {
	// Authenticates a user to login into their account
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Creates a user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves default token for defualt user
	GetDefaultToken(ctx context.Context, in *GetDefaultTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Retrieves a user profile
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*Profile, error)
	// Authenticates a user to check if they are logged in and with valid token.
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// Lists all user in the database. Admins only
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (AccountAPI_ListUsersClient, error)
	// Admin section
	// Authenticates admins when they log in to their account
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Creates a new admin
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetAdmin retrieves an admin profile
	GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*Admin, error)
	// Authenticates admin to check if they are logged in and have valid token
	AuthenticateAdmin(ctx context.Context, in *AuthenticateAdminRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type accountAPIClient struct {
	cc *grpc.ClientConn
}

func NewAccountAPIClient(cc *grpc.ClientConn) AccountAPIClient {
	return &accountAPIClient{cc}
}

func (c *accountAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetDefaultToken(ctx context.Context, in *GetDefaultTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/GetDefaultToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/AuthenticateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (AccountAPI_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountAPI_serviceDesc.Streams[0], "/rupacinema.account.AccountAPI/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountAPIListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountAPI_ListUsersClient interface {
	Recv() (*Profile, error)
	grpc.ClientStream
}

type accountAPIListUsersClient struct {
	grpc.ClientStream
}

func (x *accountAPIListUsersClient) Recv() (*Profile, error) {
	m := new(Profile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountAPIClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/LoginAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/CreateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*Admin, error) {
	out := new(Admin)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) AuthenticateAdmin(ctx context.Context, in *AuthenticateAdminRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/rupacinema.account.AccountAPI/AuthenticateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServer is the server API for AccountAPI service.
type AccountAPIServer interface {
	// Authenticates a user to login into their account
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Creates a user
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	// Retrieves default token for defualt user
	GetDefaultToken(context.Context, *GetDefaultTokenRequest) (*LoginResponse, error)
	// Retrieves a user profile
	GetUser(context.Context, *GetUserRequest) (*Profile, error)
	// Authenticates a user to check if they are logged in and with valid token.
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateResponse, error)
	// Lists all user in the database. Admins only
	ListUsers(*ListUsersRequest, AccountAPI_ListUsersServer) error
	// Admin section
	// Authenticates admins when they log in to their account
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginResponse, error)
	// Creates a new admin
	CreateAdmin(context.Context, *CreateAdminRequest) (*empty.Empty, error)
	// GetAdmin retrieves an admin profile
	GetAdmin(context.Context, *GetAdminRequest) (*Admin, error)
	// Authenticates admin to check if they are logged in and have valid token
	AuthenticateAdmin(context.Context, *AuthenticateAdminRequest) (*AuthenticateResponse, error)
}

func RegisterAccountAPIServer(s *grpc.Server, srv AccountAPIServer) {
	s.RegisterService(&_AccountAPI_serviceDesc, srv)
}

func _AccountAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetDefaultToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetDefaultToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/GetDefaultToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetDefaultToken(ctx, req.(*GetDefaultTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountAPIServer).ListUsers(m, &accountAPIListUsersServer{stream})
}

type AccountAPI_ListUsersServer interface {
	Send(*Profile) error
	grpc.ServerStream
}

type accountAPIListUsersServer struct {
	grpc.ServerStream
}

func (x *accountAPIListUsersServer) Send(m *Profile) error {
	return x.ServerStream.SendMsg(m)
}

func _AccountAPI_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/LoginAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/CreateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetAdmin(ctx, req.(*GetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_AuthenticateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).AuthenticateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rupacinema.account.AccountAPI/AuthenticateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).AuthenticateAdmin(ctx, req.(*AuthenticateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rupacinema.account.AccountAPI",
	HandlerType: (*AccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountAPI_Login_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AccountAPI_CreateUser_Handler,
		},
		{
			MethodName: "GetDefaultToken",
			Handler:    _AccountAPI_GetDefaultToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountAPI_GetUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _AccountAPI_AuthenticateUser_Handler,
		},
		{
			MethodName: "LoginAdmin",
			Handler:    _AccountAPI_LoginAdmin_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _AccountAPI_CreateAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _AccountAPI_GetAdmin_Handler,
		},
		{
			MethodName: "AuthenticateAdmin",
			Handler:    _AccountAPI_AuthenticateAdmin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _AccountAPI_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}
